/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.HomeAddress;
import Model.HomeAddressHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author Danny
 */
public class CreatePanelHomeAddress extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanelHomeAddress
     */
    
    HomeAddressHistory history_h;

    public CreatePanelHomeAddress(HomeAddressHistory history_h) {
        initComponents();
        this.history_h=history_h;    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtHAZipCode = new javax.swing.JTextField();
        txtHACity = new javax.swing.JTextField();
        txtHAddress1 = new javax.swing.JTextField();
        txtHALocality = new javax.swing.JTextField();
        lblTitleHomeAdd = new javax.swing.JLabel();
        txtHAddress2 = new javax.swing.JTextField();
        lblAddLine2 = new javax.swing.JLabel();
        btnSaveHAAddress = new javax.swing.JButton();
        lblAddLine1 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblLocality = new javax.swing.JLabel();
        lblZipCode = new javax.swing.JLabel();
        txtHAName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();

        txtHAZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAZipCodeActionPerformed(evt);
            }
        });

        txtHACity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHACityActionPerformed(evt);
            }
        });

        txtHAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddress1ActionPerformed(evt);
            }
        });

        txtHALocality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHALocalityActionPerformed(evt);
            }
        });

        lblTitleHomeAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleHomeAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleHomeAdd.setText("CREATE HOME ADDRESS");

        txtHAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddress2ActionPerformed(evt);
            }
        });

        lblAddLine2.setText("Address line 2:");

        btnSaveHAAddress.setText("CREATE HOME ADDRESS");
        btnSaveHAAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveHAAddressActionPerformed(evt);
            }
        });

        lblAddLine1.setText("Address line 1:");

        lblCity.setText("City:");

        lblLocality.setText("Locality:");

        lblZipCode.setText("Zip code:");

        txtHAName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHANameActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitleHomeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 337, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddLine1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblZipCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddLine2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocality, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHAZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(txtHALocality, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(txtHAddress1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(txtHAddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(txtHAName, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(btnSaveHAAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtHACity, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(258, 258, 258))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine1)
                    .addComponent(txtHAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddLine2)
                    .addComponent(txtHAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocality)
                    .addComponent(txtHALocality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblZipCode))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHACity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHAZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(btnSaveHAAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHAZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAZipCodeActionPerformed

    private void txtHACityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHACityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHACityActionPerformed

    private void txtHAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddress1ActionPerformed

    private void txtHALocalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHALocalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHALocalityActionPerformed

    private void txtHAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddress2ActionPerformed

    private void btnSaveHAAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveHAAddressActionPerformed
        // TODO add your handling code here:

        String name = txtHAName.getText();
        String addLine1 = txtHAddress1.getText();
        String addLine2 = txtHAddress2.getText();
        String City = txtHACity.getText();
        String Locality = txtHALocality.getText();
        String Zip_code= txtHAZipCode.getText();

        HomeAddress ha1 = history_h.addNewHomeAddress();

        ha1.setName(name);
        ha1.setAddLine1(addLine1);
        ha1.setAddLine2(addLine2);
        ha1.setLocality(Locality);
        ha1.setCity(City);
        ha1.setZip_code(Zip_code);

        JOptionPane.showMessageDialog(this,"New Home Address for " + name + " Created ");

        txtHAName.setText("");
        txtHAddress1.setText("");
        txtHAddress2.setText("");
        txtHACity.setText("");
        txtHALocality.setText("");
        txtHAZipCode.setText("");

    }//GEN-LAST:event_btnSaveHAAddressActionPerformed

    private void txtHANameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHANameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHANameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveHAAddress;
    private javax.swing.JLabel lblAddLine1;
    private javax.swing.JLabel lblAddLine2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblLocality;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitleHomeAdd;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTextField txtHACity;
    private javax.swing.JTextField txtHALocality;
    private javax.swing.JTextField txtHAName;
    private javax.swing.JTextField txtHAZipCode;
    private javax.swing.JTextField txtHAddress1;
    private javax.swing.JTextField txtHAddress2;
    // End of variables declaration//GEN-END:variables
}
