/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.HomeAddressHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.HomeAddress;



/**
 *
 * @author Danny
 */
public class ViewPanelHomeAddress extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanelHomeAddress
     */
    HomeAddressHistory history_h;
    
    public ViewPanelHomeAddress(HomeAddressHistory history_h) {
        initComponents();
        
        this.history_h = history_h;
        populateTableH();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHomeAddress = new javax.swing.JTable();
        btnDeleteHAAddress = new javax.swing.JButton();
        btnViewHAAddress = new javax.swing.JButton();
        lblAddLine1 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblLocality = new javax.swing.JLabel();
        txtHAZipCode = new javax.swing.JTextField();
        lblZipCode = new javax.swing.JLabel();
        txtHACity = new javax.swing.JTextField();
        txtHAName = new javax.swing.JTextField();
        txtHAddress1 = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtHALocality = new javax.swing.JTextField();
        txtHAddress2 = new javax.swing.JTextField();
        lblAddLine2 = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("VIEW HOME ADDRESS");

        tblHomeAddress.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address Line 1", "Address Line 2", "Locality", "City"
            }
        ));
        jScrollPane1.setViewportView(tblHomeAddress);

        btnDeleteHAAddress.setText("Delete Address");
        btnDeleteHAAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHAAddressActionPerformed(evt);
            }
        });

        btnViewHAAddress.setText("View Address");
        btnViewHAAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHAAddressActionPerformed(evt);
            }
        });

        lblAddLine1.setText("Address line 1:");

        lblCity.setText("City:");

        lblLocality.setText("Locality:");

        txtHAZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAZipCodeActionPerformed(evt);
            }
        });

        lblZipCode.setText("Zip code:");

        txtHACity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHACityActionPerformed(evt);
            }
        });

        txtHAName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHANameActionPerformed(evt);
            }
        });

        txtHAddress1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddress1ActionPerformed(evt);
            }
        });

        lblName.setText("Name:");

        txtHALocality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHALocalityActionPerformed(evt);
            }
        });

        txtHAddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAddress2ActionPerformed(evt);
            }
        });

        lblAddLine2.setText("Address line 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddLine1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblZipCode, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAddLine2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCity, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocality, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHAZipCode)
                                .addComponent(txtHALocality)
                                .addComponent(txtHAddress1)
                                .addComponent(txtHAddress2)
                                .addComponent(txtHAName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHACity, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnViewHAAddress)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteHAAddress))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewHAAddress)
                    .addComponent(btnDeleteHAAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHAName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLine1)
                    .addComponent(txtHAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddLine2)
                    .addComponent(txtHAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocality)
                    .addComponent(txtHALocality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblZipCode))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtHACity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHAZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHAZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAZipCodeActionPerformed

    private void btnDeleteHAAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHAAddressActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblHomeAddress.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        DefaultTableModel model1 = (DefaultTableModel) tblHomeAddress.getModel();
        HomeAddress selectedHomeAddress = (HomeAddress) model1.getValueAt(selectedRowIndex, 0);
        history_h.deleteHAddress(selectedHomeAddress);


        JOptionPane.showMessageDialog(this, "Home Address deleted.");
        populateTableH();

        txtHAName.setText("");
        txtHAddress1.setText("");
        txtHAddress2.setText("");
        txtHALocality.setText("");
        txtHACity.setText("");
        txtHAZipCode.setText("");
        }

        private void populateTableH() {
        DefaultTableModel model1 = (DefaultTableModel) tblHomeAddress.getModel();
        model1.setRowCount(0);

        for (HomeAddress ha1: history_h.getHistory_h()){
    
        Object[] row = new Object[5];
        row[0] = ha1;
        row[1] = ha1.getAddLine1();
        row[2] = ha1.getAddLine2();
        row[3] = ha1.getLocality();
        row[4] = ha1.getCity();

        model1.addRow(row);
   
        }

    }//GEN-LAST:event_btnDeleteHAAddressActionPerformed

    private void txtHAddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddress2ActionPerformed

    private void txtHALocalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHALocalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHALocalityActionPerformed

    private void txtHAddress1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAddress1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAddress1ActionPerformed

    private void txtHANameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHANameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHANameActionPerformed

    private void btnViewHAAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHAAddressActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblHomeAddress.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please a select a row to view");
            return;
        }

        DefaultTableModel model1 = (DefaultTableModel)tblHomeAddress.getModel();
        HomeAddress selectedHomeAddress = (HomeAddress)model1.getValueAt(selectedRowIndex,0);

        txtHAName.setText(String.valueOf(selectedHomeAddress.getName()));
        txtHAddress1.setText(String.valueOf(selectedHomeAddress.getAddLine1()));
        txtHAddress2.setText(String.valueOf(selectedHomeAddress.getAddLine2()));
        txtHALocality.setText(String.valueOf(selectedHomeAddress.getLocality()));
        txtHACity.setText(String.valueOf(selectedHomeAddress.getCity()));
        txtHAZipCode.setText(String.valueOf(selectedHomeAddress.getZip_code()));

    }//GEN-LAST:event_btnViewHAAddressActionPerformed

    private void txtHACityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHACityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHACityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteHAAddress;
    private javax.swing.JButton btnViewHAAddress;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddLine1;
    private javax.swing.JLabel lblAddLine2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblLocality;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblZipCode;
    private javax.swing.JTable tblHomeAddress;
    private javax.swing.JTextField txtHACity;
    private javax.swing.JTextField txtHALocality;
    private javax.swing.JTextField txtHAName;
    private javax.swing.JTextField txtHAZipCode;
    private javax.swing.JTextField txtHAddress1;
    private javax.swing.JTextField txtHAddress2;
    // End of variables declaration//GEN-END:variables

}
